version: 2.1

orbs:
  python: circleci/python@1.4.0

jobs:
  pypi_publish:
    executor: python/default
    steps:
      - checkout # checkout source code to working directory
      - run:
          command: | # create whl, install twine and publish to PyPI
            echo $PYPI_USERNAME

workflows:
  main:
    jobs:
      - python/test:
          test-tool: unittest
      - pypi_publish:
          requires:
            - python/test
