version: 2.1

orbs:
  python: circleci/python@1.4.0

jobs:
  build:
    executor: python/default
    steps:
      - checkout # get the code from the main branch
      - python/install-deps # pip install based on requiremnts.txt
      - python/test

workflow:
  main:
    jobs:
      - test_src_code
