version: 2.1

jobs:
  test:
    docker:
      - image: cimg/python:3.9.7
    steps:
      - checkout
      - run: python --version
      - run:
        name: Install dependencies
        command: pip install -r requirements.txt
      -run:
        name: Run Tests
        command: python -m unittest

workflows:
  test-deploy:
    jobs:
      - test
