version: 2.1

orbs:
  python: circleci/python@1.4.0

jobs:
  pypi_publish:
    executor: python/default
    steps:
      - checkout # checkout source code to working directory
      - run:
          command: | # create whl, install twine and publish to PyPI
            pip install twine wheel
            python setup.py sdist bdist_wheel
            twine upload --verbose -u $PYPI_USERNAME -p $PYPI_PASSWORD dist/*

workflows:
  main:
    jobs:
      - python/test:
          test-tool: unittest
      - pypi_publish:
          requires:
            - python/test
